### ISSUE TITLE
ScrollView

### ISSUE THREAD

**Issue by PatientLiu** [ShelinShelin/XLVideoPlayer#5]
如果在ScrollView铺一个XLVideoPlayer竖屏后再切到横屏他的view层级会脱离ScrollView的控制，    [self.keyWindow addSubview:self];看到您写这个了，业务的问题已经解决，顺便符几种方案吧，传入ScrollView的自己创建的子view或者rac监控机器方向楼，keyWindow了解铺在视图最上，但是view.top应该也是可以的但是没有测试。库很方便，谢谢

**Comment by ShelinShelin** [comment]
加载keyWindow主要是考虑到放在所有视图的最上层

**Comment by PatientLiu** [comment]
self.keyWindow 加载后会导致视图层级错误。这个view的锚点会落在当前视图的window上，如果我在ScrollView上一个固定位置设置XLVideoPlayerView旋转后再次滑动ScrollView因为锚点已经落在window上。所以。。。。。
